[project]
name = "raenim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "addict>=2.4.0",
    "manim>=0.19.2",
    "opencv-python>=4.13.0.90",
    "noise>=1.2.2",
]
